{% set name = "trackastra" %}
{% set version = "0.5.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/weigertlab/trackastra/archive/refs/tags/{{ version }}.tar.gz
  sha256: 88476d2cd445b700e21aad656165c484dee6ec4cf318bf29c4c65b815fe6419c

build:
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TRACKASTRA={{ version }}  # [unix]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TRACKASTRA={{ version }}"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - trackastra = trackastra.cli:cli

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - scikit-image
    - pytorch
    - torchvision
    - pyyaml
    - edt
    - joblib
    - lz4
    - imagecodecs >=2023.7.10
    - chardet
    - dask
    - numba
    - geff >=1
    - tqdm
    - requests
    - psutil
    - platformdirs
    - motile >=1.0
    - ilpy >=0.6
  run_constrained:
    - libblas * *newaccelerate  # [osx]

test:
  imports:
    - trackastra
  commands:
    - pip check
    - python -c "import trackastra; assert trackastra.__version__ == '{{ version }}'"
  requires:
    - pip
    - python

about:
  home: https://github.com/weigertlab/trackastra
  summary: Tracking by Association with Transformers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bentaculum
